import { Course, Round, Topic, Module, UserProgress, CourseAccess } from "@/types";

// Mock Users
export const mockUsers = [
  {
    id: "user-1",
    email: "learner@example.com",
    name: "Mohit",
    createdAt: new Date("2024-01-01"),
  },
];

// Mock Courses
export const mockCourses: Course[] = [
  {
    id: "course-1",
    title: "TCS Interview Preparation",
    description: "Complete preparation guide for TCS interview rounds",
    companyName: "TCS",
    type: "company-specific",
    thumbnailUrl: "/tcs-logo.png",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "course-2",
    title: "Infosys Interview Preparation",
    description: "Comprehensive Infosys interview preparation course",
    companyName: "Infosys",
    type: "company-specific",
    thumbnailUrl: "/infosys-logo.png",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "course-3",
    title: "Java Full Stack Bootcamp",
    description: "Master Java full stack development",
    type: "skill-based",
    thumbnailUrl: "/java-logo.png",
    createdAt: new Date("2024-01-01"),
  },
];

// Mock Rounds (for company-specific courses)
export const mockRounds: Round[] = [
  {
    id: "round-1-1",
    courseId: "course-1",
    title: "Round 1: Aptitude & Reasoning",
    description: "Master quantitative aptitude, logical reasoning, and verbal ability",
    order: 1,
    learningOutcomes: [
      "Solve complex quantitative problems quickly",
      "Master logical reasoning patterns",
      "Improve verbal comprehension skills",
      "Practice time management techniques",
    ],
  },
  {
    id: "round-1-2",
    courseId: "course-1",
    title: "Round 2: Technical MCQ",
    description: "Technical multiple choice questions on programming and computer science",
    order: 2,
    learningOutcomes: [
      "Understand core programming concepts",
      "Master data structures and algorithms",
      "Learn database fundamentals",
      "Grasp operating system concepts",
    ],
  },
  {
    id: "round-1-3",
    courseId: "course-1",
    title: "Round 3: Coding Round",
    description: "Live coding assessment with problem-solving challenges",
    order: 3,
    learningOutcomes: [
      "Write efficient algorithms",
      "Practice common coding patterns",
      "Debug code effectively",
      "Optimize time and space complexity",
    ],
  },
  {
    id: "round-2-1",
    courseId: "course-2",
    title: "Round 1: Online Assessment",
    description: "Aptitude, reasoning, and basic technical assessment",
    order: 1,
    learningOutcomes: [
      "Excel in aptitude tests",
      "Master logical puzzles",
      "Answer technical MCQs confidently",
    ],
  },
  {
    id: "round-2-2",
    courseId: "course-2",
    title: "Round 2: Technical Interview",
    description: "In-depth technical interview preparation",
    order: 2,
    learningOutcomes: [
      "Explain technical concepts clearly",
      "Solve coding problems on whiteboard",
      "Discuss project experiences effectively",
    ],
  },
  {
    id: "round-2-3",
    courseId: "course-2",
    title: "Round 3: HR Interview",
    description: "HR interview preparation and soft skills",
    order: 3,
    learningOutcomes: [
      "Answer behavioral questions confidently",
      "Showcase leadership and teamwork skills",
      "Negotiate salary and benefits effectively",
    ],
  },
  // Java Bootcamp Sections (using "Part" naming for skill-based course)
  {
    id: "section-3-1",
    courseId: "course-3",
    title: "Part 1: Java Fundamentals",
    description: "Master core Java programming concepts",
    order: 1,
    learningOutcomes: [
      "Write Java programs confidently",
      "Understand object-oriented programming",
      "Work with Java data structures",
    ],
  },
  {
    id: "section-3-2",
    courseId: "course-3",
    title: "Part 2: Backend Development",
    description: "Build backend applications with Spring Boot",
    order: 2,
    learningOutcomes: [
      "Create REST APIs with Spring Boot",
      "Work with databases using JPA",
      "Implement authentication and security",
    ],
  },
  {
    id: "section-3-3",
    courseId: "course-3",
    title: "Part 3: Frontend & Deployment",
    description: "Complete full stack development and deployment",
    order: 3,
    learningOutcomes: [
      "Build frontend with React",
      "Connect frontend to backend APIs",
      "Deploy applications to cloud platforms",
    ],
  },
];

// Mock Topics
export const mockTopics: Topic[] = [
  // TCS Round 1 Topics
  {
    id: "topic-1-1",
    roundId: "round-1-1",
    courseId: "course-1",
    title: "Quantitative Aptitude",
    order: 1,
  },
  {
    id: "topic-1-2",
    roundId: "round-1-1",
    courseId: "course-1",
    title: "Logical Reasoning",
    order: 2,
  },
  {
    id: "topic-1-3",
    roundId: "round-1-1",
    courseId: "course-1",
    title: "Verbal Ability",
    order: 3,
  },
  // TCS Round 2 Topics
  {
    id: "topic-2-1",
    roundId: "round-1-2",
    courseId: "course-1",
    title: "Programming Fundamentals",
    order: 1,
  },
  {
    id: "topic-2-2",
    roundId: "round-1-2",
    courseId: "course-1",
    title: "Data Structures",
    order: 2,
  },
  // TCS Round 3 Topics
  {
    id: "topic-3-1",
    roundId: "round-1-3",
    courseId: "course-1",
    title: "Array and String Problems",
    order: 1,
  },
  {
    id: "topic-3-2",
    roundId: "round-1-3",
    courseId: "course-1",
    title: "Dynamic Programming",
    order: 2,
  },
  {
    id: "topic-3-3",
    roundId: "round-1-3",
    courseId: "course-1",
    title: "Sorting and Searching",
    order: 3,
  },
  {
    id: "topic-3-4",
    roundId: "round-1-3",
    courseId: "course-1",
    title: "Recursion and Backtracking",
    order: 4,
  },
  {
    id: "topic-3-5",
    roundId: "round-1-3",
    courseId: "course-1",
    title: "Trees and Graphs",
    order: 5,
  },
  // Infosys Round 1 Topics
  {
    id: "topic-4-1",
    roundId: "round-2-1",
    courseId: "course-2",
    title: "Aptitude Basics",
    order: 1,
  },
  {
    id: "topic-4-2",
    roundId: "round-2-1",
    courseId: "course-2",
    title: "Logical Reasoning",
    order: 2,
  },
  {
    id: "topic-4-3",
    roundId: "round-2-1",
    courseId: "course-2",
    title: "Technical MCQ Practice",
    order: 3,
  },
  // Infosys Round 2 Topics
  {
    id: "topic-4-4",
    roundId: "round-2-2",
    courseId: "course-2",
    title: "Core Programming Concepts",
    order: 1,
  },
  {
    id: "topic-4-5",
    roundId: "round-2-2",
    courseId: "course-2",
    title: "Problem Solving Techniques",
    order: 2,
  },
  // Infosys Round 3 Topics
  {
    id: "topic-4-6",
    roundId: "round-2-3",
    courseId: "course-2",
    title: "Behavioral Questions",
    order: 1,
  },
  {
    id: "topic-4-7",
    roundId: "round-2-3",
    courseId: "course-2",
    title: "Communication Skills",
    order: 2,
  },
  // Java Bootcamp - Part 1 Topics
  {
    id: "topic-5-1",
    roundId: "section-3-1",
    courseId: "course-3",
    title: "Java Basics",
    order: 1,
  },
  {
    id: "topic-5-2",
    roundId: "section-3-1",
    courseId: "course-3",
    title: "OOP Concepts",
    order: 2,
  },
  {
    id: "topic-5-3",
    roundId: "section-3-1",
    courseId: "course-3",
    title: "Collections Framework",
    order: 3,
  },
  // Java Bootcamp - Part 2 Topics
  {
    id: "topic-5-4",
    roundId: "section-3-2",
    courseId: "course-3",
    title: "Spring Boot Framework",
    order: 1,
  },
  {
    id: "topic-5-5",
    roundId: "section-3-2",
    courseId: "course-3",
    title: "Database Integration",
    order: 2,
  },
  {
    id: "topic-5-6",
    roundId: "section-3-2",
    courseId: "course-3",
    title: "RESTful APIs",
    order: 3,
  },
  // Java Bootcamp - Part 3 Topics
  {
    id: "topic-5-7",
    roundId: "section-3-3",
    courseId: "course-3",
    title: "React Fundamentals",
    order: 1,
  },
  {
    id: "topic-5-8",
    roundId: "section-3-3",
    courseId: "course-3",
    title: "Frontend-Backend Integration",
    order: 2,
  },
  {
    id: "topic-5-9",
    roundId: "section-3-3",
    courseId: "course-3",
    title: "Cloud Deployment",
    order: 3,
  },
];

// Mock Modules
export const mockModules: Module[] = [
  // Quantitative Aptitude Modules
  {
    id: "module-1-1",
    topicId: "topic-1-1",
    title: "Introduction to Number Systems",
    description: "Learn the basics of number systems and conversions",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 900, // 15 minutes
    order: 1,
  },
  {
    id: "module-1-2",
    topicId: "topic-1-1",
    title: "Percentages and Ratios",
    description: "Master percentage calculations and ratio problems",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200, // 20 minutes
    order: 2,
  },
  {
    id: "module-1-3",
    topicId: "topic-1-1",
    title: "Time and Work Problems",
    description: "Solve time and work problems efficiently",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800, // 30 minutes
    order: 3,
  },
  // Logical Reasoning Modules
  {
    id: "module-2-1",
    topicId: "topic-1-2",
    title: "Series and Patterns",
    description: "Identify patterns and complete series",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 900,
    order: 1,
  },
  {
    id: "module-2-2",
    topicId: "topic-1-2",
    title: "Coding-Decoding",
    description: "Master coding and decoding techniques",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200,
    order: 2,
  },
  // Verbal Ability Modules
  {
    id: "module-3-1",
    topicId: "topic-1-3",
    title: "Reading Comprehension",
    description: "Improve reading speed and comprehension",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1500,
    order: 1,
  },
  // Programming Fundamentals Modules
  {
    id: "module-4-1",
    topicId: "topic-2-1",
    title: "Variables and Data Types",
    description: "Understanding variables and data types in programming",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200,
    order: 1,
  },
  {
    id: "module-4-2",
    topicId: "topic-2-1",
    title: "Control Structures",
    description: "Master if-else, loops, and switch statements",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 2,
  },
  // Data Structures Modules
  {
    id: "module-5-1",
    topicId: "topic-2-2",
    title: "Arrays and Linked Lists",
    description: "Understanding array and linked list data structures",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 1,
  },
  // TCS Round 3 - Array and String Problems Modules
  {
    id: "module-3-1",
    topicId: "topic-3-1",
    title: "Array Manipulation Techniques",
    description: "Learn essential array manipulation techniques and algorithms",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 1,
  },
  {
    id: "module-3-2",
    topicId: "topic-3-1",
    title: "Two Pointer and Sliding Window",
    description: "Master two pointer technique and sliding window approach",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 2,
  },
  {
    id: "module-3-3",
    topicId: "topic-3-1",
    title: "String Algorithms and Pattern Matching",
    description: "Understanding string manipulation and pattern matching algorithms",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1900,
    order: 3,
  },
  // TCS Round 3 - Dynamic Programming Modules
  {
    id: "module-3-4",
    topicId: "topic-3-2",
    title: "Introduction to Dynamic Programming",
    description: "Understanding DP concepts and when to use them",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2200,
    order: 1,
  },
  {
    id: "module-3-5",
    topicId: "topic-3-2",
    title: "Common DP Patterns",
    description: "Learn common dynamic programming patterns and problems",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 2,
  },
  {
    id: "module-3-6",
    topicId: "topic-3-2",
    title: "DP Optimization Techniques",
    description: "Advanced optimization techniques in dynamic programming",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2000,
    order: 3,
  },
  // TCS Round 3 - Sorting and Searching Modules
  {
    id: "module-3-7",
    topicId: "topic-3-3",
    title: "Sorting Algorithms Overview",
    description: "Understanding various sorting algorithms and their complexities",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-3-8",
    topicId: "topic-3-3",
    title: "Binary Search and Variations",
    description: "Master binary search technique and its variations",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 2,
  },
  {
    id: "module-3-9",
    topicId: "topic-3-3",
    title: "Advanced Searching Techniques",
    description: "Learn ternary search and other advanced searching methods",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1900,
    order: 3,
  },
  // TCS Round 3 - Recursion and Backtracking Modules
  {
    id: "module-3-10",
    topicId: "topic-3-4",
    title: "Recursion Fundamentals",
    description: "Understanding recursion and recursive problem solving",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1700,
    order: 1,
  },
  {
    id: "module-3-11",
    topicId: "topic-3-4",
    title: "Backtracking Patterns",
    description: "Learn backtracking technique for constraint satisfaction problems",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2200,
    order: 2,
  },
  {
    id: "module-3-12",
    topicId: "topic-3-4",
    title: "Common Backtracking Problems",
    description: "Solving N-Queens, Sudoku, and other classic problems",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 3,
  },
  // TCS Round 3 - Trees and Graphs Modules
  {
    id: "module-3-13",
    topicId: "topic-3-5",
    title: "Tree Data Structures and Traversals",
    description: "Understanding trees, binary trees, and traversal techniques",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-3-14",
    topicId: "topic-3-5",
    title: "Binary Search Trees and AVL Trees",
    description: "Learn about BST operations and self-balancing trees",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2300,
    order: 2,
  },
  {
    id: "module-3-15",
    topicId: "topic-3-5",
    title: "Graph Algorithms - BFS and DFS",
    description: "Master graph traversal algorithms and their applications",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2500,
    order: 3,
  },
  {
    id: "module-3-16",
    topicId: "topic-3-5",
    title: "Shortest Path Algorithms",
    description: "Learn Dijkstra's, Bellman-Ford, and Floyd-Warshall algorithms",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2600,
    order: 4,
  },
  // Infosys - Aptitude Basics Modules
  {
    id: "module-7-1",
    topicId: "topic-4-1",
    title: "Number Systems and Conversions",
    description: "Understanding different number systems",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200,
    order: 1,
  },
  {
    id: "module-7-2",
    topicId: "topic-4-1",
    title: "Percentages and Profit-Loss",
    description: "Master percentage and profit-loss calculations",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1500,
    order: 2,
  },
  // Infosys - Logical Reasoning Modules
  {
    id: "module-7-3",
    topicId: "topic-4-2",
    title: "Puzzles and Pattern Recognition",
    description: "Solve logical puzzles efficiently",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 1,
  },
  {
    id: "module-7-4",
    topicId: "topic-4-2",
    title: "Syllogisms and Statements",
    description: "Master logical deduction techniques",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200,
    order: 2,
  },
  // Infosys - Technical MCQ Practice Modules
  {
    id: "module-7-5",
    topicId: "topic-4-3",
    title: "C Programming Basics",
    description: "Core concepts of C programming",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-7-6",
    topicId: "topic-4-3",
    title: "Database Fundamentals",
    description: "SQL and database concepts",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 2,
  },
  // Infosys - Core Programming Concepts Modules
  {
    id: "module-7-7",
    topicId: "topic-4-4",
    title: "OOP Principles",
    description: "Object-oriented programming fundamentals",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 1,
  },
  {
    id: "module-7-8",
    topicId: "topic-4-4",
    title: "Data Structures Overview",
    description: "Essential data structures explained",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2700,
    order: 2,
  },
  // Infosys - Problem Solving Techniques Modules
  {
    id: "module-7-9",
    topicId: "topic-4-5",
    title: "Algorithmic Thinking",
    description: "Develop problem-solving mindset",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-7-10",
    topicId: "topic-4-5",
    title: "Code Optimization",
    description: "Write efficient and optimal code",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 2,
  },
  // Infosys - Behavioral Questions Modules
  {
    id: "module-7-11",
    topicId: "topic-4-6",
    title: "Common HR Questions",
    description: "Prepare for frequently asked HR questions",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1500,
    order: 1,
  },
  {
    id: "module-7-12",
    topicId: "topic-4-6",
    title: "STAR Method for Interviews",
    description: "Master the STAR technique for behavioral questions",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200,
    order: 2,
  },
  // Infosys - Communication Skills Modules
  {
    id: "module-7-13",
    topicId: "topic-4-7",
    title: "Effective Communication",
    description: "Improve verbal and non-verbal communication",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 1,
  },
  {
    id: "module-7-14",
    topicId: "topic-4-7",
    title: "Body Language and Confidence",
    description: "Master professional body language",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1500,
    order: 2,
  },
  // Java Bootcamp - Java Basics Modules
  {
    id: "module-6-1",
    topicId: "topic-5-1",
    title: "Java Installation and Setup",
    description: "Setting up Java development environment",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 900,
    order: 1,
  },
  {
    id: "module-6-2",
    topicId: "topic-5-1",
    title: "Your First Java Program",
    description: "Writing and running your first Java program",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1200,
    order: 2,
  },
  {
    id: "module-6-3",
    topicId: "topic-5-1",
    title: "Variables and Data Types",
    description: "Understanding Java data types and variables",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1500,
    order: 3,
  },
  {
    id: "module-6-4",
    topicId: "topic-5-1",
    title: "Control Flow Statements",
    description: "Master if-else, loops, and switch statements",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 4,
  },
  // Java Bootcamp - OOP Concepts Modules
  {
    id: "module-6-5",
    topicId: "topic-5-2",
    title: "Classes and Objects",
    description: "Understanding OOP fundamentals",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-6-6",
    topicId: "topic-5-2",
    title: "Inheritance and Polymorphism",
    description: "Master OOP inheritance and polymorphism",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 2,
  },
  {
    id: "module-6-7",
    topicId: "topic-5-2",
    title: "Abstraction and Encapsulation",
    description: "Learn abstraction and encapsulation principles",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 3,
  },
  // Java Bootcamp - Collections Framework Modules
  {
    id: "module-6-8",
    topicId: "topic-5-3",
    title: "List and ArrayList",
    description: "Working with Java Lists",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1500,
    order: 1,
  },
  {
    id: "module-6-9",
    topicId: "topic-5-3",
    title: "Sets and Maps",
    description: "Understanding Set and Map collections",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 2,
  },
  // Java Bootcamp - Spring Boot Framework Modules
  {
    id: "module-6-10",
    topicId: "topic-5-4",
    title: "Spring Boot Introduction",
    description: "Getting started with Spring Boot",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 1,
  },
  {
    id: "module-6-11",
    topicId: "topic-5-4",
    title: "Spring Boot Project Setup",
    description: "Creating your first Spring Boot project",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 2,
  },
  {
    id: "module-6-12",
    topicId: "topic-5-4",
    title: "Dependency Injection",
    description: "Understanding Spring dependency injection",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 3,
  },
  // Java Bootcamp - Database Integration Modules
  {
    id: "module-6-13",
    topicId: "topic-5-5",
    title: "JPA and Hibernate Basics",
    description: "Introduction to JPA and Hibernate",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2700,
    order: 1,
  },
  {
    id: "module-6-14",
    topicId: "topic-5-5",
    title: "Database CRUD Operations",
    description: "Implementing Create, Read, Update, Delete operations",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 3000,
    order: 2,
  },
  // Java Bootcamp - RESTful APIs Modules
  {
    id: "module-6-15",
    topicId: "topic-5-6",
    title: "REST API Fundamentals",
    description: "Understanding RESTful web services",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-6-16",
    topicId: "topic-5-6",
    title: "Building REST Controllers",
    description: "Creating REST API endpoints",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2700,
    order: 2,
  },
  {
    id: "module-6-17",
    topicId: "topic-5-6",
    title: "API Testing with Postman",
    description: "Testing REST APIs effectively",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 3,
  },
  // Java Bootcamp - React Fundamentals Modules
  {
    id: "module-6-18",
    topicId: "topic-5-7",
    title: "React Setup and JSX",
    description: "Getting started with React",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 1,
  },
  {
    id: "module-6-19",
    topicId: "topic-5-7",
    title: "Components and Props",
    description: "Building React components",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 2,
  },
  {
    id: "module-6-20",
    topicId: "topic-5-7",
    title: "State and Hooks",
    description: "Managing state with React hooks",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2700,
    order: 3,
  },
  // Java Bootcamp - Frontend-Backend Integration Modules
  {
    id: "module-6-21",
    topicId: "topic-5-8",
    title: "Axios and API Integration",
    description: "Connecting React to backend APIs",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2400,
    order: 1,
  },
  {
    id: "module-6-22",
    topicId: "topic-5-8",
    title: "Authentication Flow",
    description: "Implementing user authentication",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 3000,
    order: 2,
  },
  // Java Bootcamp - Cloud Deployment Modules
  {
    id: "module-6-23",
    topicId: "topic-5-9",
    title: "Heroku Deployment",
    description: "Deploying Spring Boot to Heroku",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 2100,
    order: 1,
  },
  {
    id: "module-6-24",
    topicId: "topic-5-9",
    title: "Environment Configuration",
    description: "Managing environment variables and configs",
    videoUrl: "https://www.youtube.com/embed/9nKMzeqdS4g",
    duration: 1800,
    order: 2,
  },
];

// Mock User Progress
export const mockUserProgress: UserProgress[] = [
  // Round 1 modules - ALL COMPLETED
  {
    id: "progress-1",
    userId: "user-1",
    moduleId: "module-1-1",
    watchedDuration: 900,
    isCompleted: true,
    lastWatchedAt: new Date("2024-01-15"),
    completedAt: new Date("2024-01-15"),
  },
  {
    id: "progress-2",
    userId: "user-1",
    moduleId: "module-1-2",
    watchedDuration: 1200,
    isCompleted: true,
    lastWatchedAt: new Date("2024-01-16"),
    completedAt: new Date("2024-01-16"),
  },
  {
    id: "progress-3",
    userId: "user-1",
    moduleId: "module-1-3",
    watchedDuration: 1800,
    isCompleted: true,
    lastWatchedAt: new Date("2024-01-17"),
    completedAt: new Date("2024-01-17"),
  },
  {
    id: "progress-4",
    userId: "user-1",
    moduleId: "module-2-1",
    watchedDuration: 900,
    isCompleted: true,
    lastWatchedAt: new Date("2024-01-18"),
    completedAt: new Date("2024-01-18"),
  },
  {
    id: "progress-5",
    userId: "user-1",
    moduleId: "module-2-2",
    watchedDuration: 1200,
    isCompleted: true,
    lastWatchedAt: new Date("2024-01-19"),
    completedAt: new Date("2024-01-19"),
  },
  {
    id: "progress-6",
    userId: "user-1",
    moduleId: "module-3-1",
    watchedDuration: 1500,
    isCompleted: true,
    lastWatchedAt: new Date("2024-01-20"),
    completedAt: new Date("2024-01-20"),
  },
  // Round 2 module - IN PROGRESS
  {
    id: "progress-7",
    userId: "user-1",
    moduleId: "module-4-1",
    watchedDuration: 600,
    isCompleted: false,
    lastWatchedAt: new Date("2024-01-21"),
  },
];

// Mock Course Access
export const mockCourseAccess: CourseAccess[] = [
  {
    id: "access-1",
    userId: "user-1",
    courseId: "course-1",
    assignedAt: new Date("2024-01-01"),
  },
  {
    id: "access-2",
    userId: "user-1",
    courseId: "course-2",
    assignedAt: new Date("2024-01-01"),
  },
  {
    id: "access-3",
    userId: "user-1",
    courseId: "course-3",
    assignedAt: new Date("2024-01-01"),
  },
];
